[package]
name = "updatedb"
version = "0.1.2"
authors = ["Rrogntudju"]
edition = "2018"

[dependencies]
walkdir = "2"
frcode = {path = "../frcode"}
winapi = {version = "0.3", features = ["fileapi"]}
serde_json = "1.0"
serde = {version = "1.0", features = ['derive']}