[package]
name = "locate"
version = "0.6.9"
authors = ["Rrogntudju"]
edition = "2021"

[dependencies]
frcode = {path = "../frcode"}
serde_json = "1.0"
clap = "4"
num-format = "0.4"
globset = "0.4"
flume = {version = "0.10", default-features = false}