[package]
name = "locate"
version = "0.1.0"
authors = ["Rrogntudju"]
edition = "2018"

[dependencies]
frcode = {path = "../frcode"}
serde_json = "1.0"
serde = {version = "1.0", features = ['derive']}
clap = "2"