[package]
name = "locate"
version = "0.6.0"
authors = ["Rrogntudju"]
edition = "2018"

[dependencies]
frcode = {path = "../frcode"}
serde_json = "1.0"
clap = {version = "2", default-features = false}
num-format = "0.4"
globset = { git = "https://github.com/BurntSushi/globset.git" }