[package]
name = "updatedb"
version = "0.1.7"
authors = ["Rrogntudju"]
edition = "2021"
build = "build/build.rs"

[dependencies]
walkdir = "2"
frcode = {path = "../frcode"}
windows = "0.19"
serde_json = "1.0"

[build-dependencies]
winres = "0.1"
windows = "0.19"
