[package]
name = "updatedb"
version = "0.1.8"
authors = ["Rrogntudju"]
edition = "2021"

[dependencies]
walkdir = "2"
frcode = {path = "../frcode"}
windows = { version = "0.42", features = ["Win32_Storage_FileSystem", "Win32_Foundation"] }
serde_json = "1.0"

